export type Lang = "ro" | "en";

export const content = {
  ro: {
    nav: { services: "Servicii", about: "Despre", process: "Proces", contact: "Contact" },
    cta: "Solicită o consultație",
    hero: {
      badge: "Chișinău, Moldova",
      title: "Afacerea ta, digitalizată și optimizată.",
      sub: "Identificăm soluțiile digitale potrivite nevoilor tale și le folosim la maximum — cu costuri minime, fără licențe inutile.",
      primary: "Solicită o consultație",
      secondary: "Vezi serviciile",
    },
    stats: [
      { k: "100%", v: "Soluții pe măsură" },
      { k: "4 pași", v: "De la analiză la suport" },
      { k: "0 jargon", v: "Explicații pe înțeles" },
    ],
    services: {
      eyebrow: "Servicii",
      title: "Ce facem pentru afacerea ta",
      sub: "De la analiză la sisteme care lucrează pentru tine.",
      items: [
        { icon: "search", title: "Analiză și consultanță de procese", desc: "Îți analizăm procesele și obiectivele și îți arătăm exact ce merită digitalizat și cu ce prioritate." },
        { icon: "layers", title: "Alegerea soluțiilor potrivite", desc: "Identificăm instrumentele SaaS care îți acoperă nevoile cu costuri minime — Microsoft 365, Google Workspace, Odoo — folosite la maximum, fără licențe inutile." },
        { icon: "bolt", title: "Implementare și automatizare", desc: "Configurăm sistemele, automatizăm sarcinile repetitive și conectăm tot ce folosești." },
        { icon: "headset", title: "Optimizare și suport", desc: "Monitorizăm, îmbunătățim și rămânem alături pe termen lung." },
      ],
    },
    values: {
      eyebrow: "De ce Switch Digital",
      title: "Cinci principii care ne ghidează",
      items: [
        { title: "Accesibilitate", desc: "Soluții pe care orice afacere și le poate permite." },
        { title: "Simplitate", desc: "Transformăm complexitatea tehnică în pași clari." },
        { title: "Transparență", desc: "Recomandări oneste, prețuri și termene clare de la început." },
        { title: "Expertiză", desc: "Alegem tehnologia potrivită nevoii tale, nu cea la modă." },
        { title: "Parteneriat", desc: "Rămânem alături de tine după implementare, nu doar în ofertă." },
      ],
    },
    process: {
      eyebrow: "Proces",
      title: "Cum lucrăm, în 4 pași",
      steps: [
        { n: "01", title: "Analiză", desc: "Înțelegem afacerea, procesele și obiectivele tale." },
        { n: "02", title: "Soluție și plan", desc: "Alegem soluția potrivită nevoii și bugetului și îți prezentăm un plan clar, cu costuri și termene." },
        { n: "03", title: "Implementare", desc: "Configurăm, integrăm și instruim echipa." },
        { n: "04", title: "Suport pe termen lung", desc: "Optimizăm continuu și rămânem disponibili." },
      ],
    },
    about: {
      eyebrow: "Despre noi",
      title: "Misiunea noastră",
      mission: "Să facem tehnologia performantă accesibilă oricărei afaceri — de la primul pas în digitalizare până la sisteme integrate.",
      founderName: "Lilia Sviriniuc",
      founderRole: "Fondator",
      founderBio: "Manager cu experiență în coordonarea echipelor mari, pe care le-a optimizat și digitalizat. Experiența ulterioară în IT i-a adăugat structura și consecvența de care are nevoie orice proces de digitalizare. A implementat un sistem ERP într-o companie medie din Moldova — și aduce aceeași abordare la Switch Digital.",
    },
    contact: {
      eyebrow: "Contact",
      title: "Scrie-ne câteva rânduri",
      sub: "Îți răspundem în cel mai scurt timp posibil.",
      name: "Nume",
      namePh: "Numele tău",
      email: "Email",
      emailPh: "email@exemplu.md",
      phone: "Telefon",
      phonePh: "+373 ...",
      message: "Mesaj",
      messagePh: "Spune-ne despre afacerea ta și ce vrei să optimizezi.",
      send: "Trimite mesajul",
      detailsTitle: "Date de contact",
      follow: "Urmărește-ne",
      note: "Formularul va fi conectat la backendul securizat în Modulul 2.",
    },
    footer: { rights: "Toate drepturile rezervate.", tagline: "Tehnologia care îți optimizează afacerea." },
  },

  en: {
    nav: { services: "Services", about: "About", process: "Process", contact: "Contact" },
    cta: "Request a consultation",
    hero: {
      badge: "Chișinău, Moldova",
      title: "Your business, digitized and optimized.",
      sub: "We identify the right digital solutions for your needs and use them to the fullest — at minimal cost, with no unnecessary licenses.",
      primary: "Request a consultation",
      secondary: "See services",
    },
    stats: [
      { k: "100%", v: "Tailored solutions" },
      { k: "4 steps", v: "From analysis to support" },
      { k: "0 jargon", v: "Clear explanations" },
    ],
    services: {
      eyebrow: "Services",
      title: "What we do for your business",
      sub: "From analysis to systems that work for you.",
      items: [
        { icon: "search", title: "Process analysis & consulting", desc: "We analyze your processes and goals and show you exactly what's worth digitizing and in what order." },
        { icon: "layers", title: "Choosing the right solutions", desc: "We identify the SaaS tools that cover your needs at minimal cost — Microsoft 365, Google Workspace, Odoo — used to the fullest, with no unnecessary licenses." },
        { icon: "bolt", title: "Implementation & automation", desc: "We set up systems, automate repetitive tasks and connect everything you use." },
        { icon: "headset", title: "Optimization & support", desc: "We monitor, improve and stay with you for the long run." },
      ],
    },
    values: {
      eyebrow: "Why Switch Digital",
      title: "Five principles that guide us",
      items: [
        { title: "Accessibility", desc: "Solutions any business can afford." },
        { title: "Simplicity", desc: "We turn technical complexity into clear steps." },
        { title: "Transparency", desc: "Honest advice, clear pricing and timelines from the start." },
        { title: "Expertise", desc: "We pick the right technology for your need, not the trendy one." },
        { title: "Partnership", desc: "We stay with you after implementation, not just in the quote." },
      ],
    },
    process: {
      eyebrow: "Process",
      title: "How we work, in 4 steps",
      steps: [
        { n: "01", title: "Analysis", desc: "We understand your business, processes and goals." },
        { n: "02", title: "Solution & plan", desc: "We choose the right solution for your need and budget and present a clear plan, with costs and timelines." },
        { n: "03", title: "Implementation", desc: "We configure, integrate and train your team." },
        { n: "04", title: "Long-term support", desc: "We keep optimizing and stay available." },
      ],
    },
    about: {
      eyebrow: "About us",
      title: "Our mission",
      mission: "To make high-performing technology accessible to any business — from the first step in digitization to integrated systems.",
      founderName: "Lilia Sviriniuc",
      founderRole: "Founder",
      founderBio: "A manager experienced in leading large teams, which she optimized and digitized. Her later IT experience added the structure and consistency any digitization process needs. She implemented an ERP system in a mid-sized company in Moldova — and brings the same approach to Switch Digital.",
    },
    contact: {
      eyebrow: "Contact",
      title: "Write us a few lines",
      sub: "We'll get back to you as soon as possible.",
      name: "Name",
      namePh: "Your name",
      email: "Email",
      emailPh: "email@example.md",
      phone: "Phone",
      phonePh: "+373 ...",
      message: "Message",
      messagePh: "Tell us about your business and what you'd like to optimize.",
      send: "Send message",
      detailsTitle: "Contact details",
      follow: "Follow us",
      note: "The form will be connected to the secure backend in Module 2.",
    },
    footer: { rights: "All rights reserved.", tagline: "Technology that optimizes your business." },
  },
} as const;

export const contactInfo = {
  email: "contact@switchdigital.md",
  phone: "+373 60 360 488",
  location: "Chișinău, Moldova",
  facebook: "https://facebook.com",
  linkedin: "https://linkedin.com",
};
