export type Lang = "ro" | "en" | "ru";

export const locales: Lang[] = ["ro", "en", "ru"];
export const defaultLocale: Lang = "ro";

export const content = {
  ro: {
    nav: { services: "Servicii", about: "Despre", process: "Proces", contact: "Contact" },
    cta: "Diagnostic gratuit",
    hero: {
      badge: "Chișinău, Moldova",
      title: "Mai puține aplicații, costuri mai mici, procese care chiar merg.",
      sub: "Pentru antreprenori și IMM-uri: identificăm soluțiile digitale potrivite și le folosim la maximum — fără licențe inutile.",
      primary: "Diagnostic gratuit",
      secondary: "Vezi serviciile",
    },
    switchRows: ["Soluții digitale", "Optimizare", "Procese stabilite"],
    stats: [
      { k: "100%", v: "Soluții pe măsură" },
      { k: "4 pași", v: "De la analiză la suport" },
      { k: "0 complicații", v: "Totul explicat simplu" },
    ],
    services: {
      eyebrow: "Servicii",
      title: "Ce facem pentru afacerea ta",
      sub: "Digitalizează azi, ca să poți folosi AI mâine.",
      items: [
        { icon: "search", title: "Analiză și consultanță de procese", desc: "Îți analizăm procesele și obiectivele și îți arătăm exact ce merită digitalizat și cu ce prioritate." },
        { icon: "layers", title: "Alegerea soluțiilor potrivite", desc: "Identificăm instrumentele SaaS care îți acoperă nevoile cu costuri minime — Microsoft 365, Google Workspace, Odoo — folosite la maximum, fără licențe inutile." },
        { icon: "bolt", title: "Implementare și automatizare", desc: "Configurăm sistemele, automatizăm sarcinile repetitive și conectăm tot ce folosești." },
        { icon: "headset", title: "Optimizare și suport", desc: "Monitorizăm, îmbunătățim și rămânem alături pe termen lung." },
        { icon: "sparkles", title: "Pregătire și integrare AI", desc: "AI funcționează doar pe procese ordonate și date curate. Le punem la punct, apoi integrăm instrumentele care aduc valoare reală." },
      ],
    },
    values: {
      eyebrow: "De ce Switch Digital",
      title: "Cinci principii care ne ghidează",
      items: [
        { title: "Accesibilitate", desc: "Soluții pe care orice afacere și le poate permite." },
        { title: "Simplitate", desc: "Transformăm complexitatea tehnică în pași clari." },
        { title: "Transparență", desc: "Recomandări oneste, prețuri și termene clare de la început." },
        { title: "Expertiză", desc: "Alegem tehnologia potrivită nevoii tale, nu cea la modă." },
        { title: "Parteneriat", desc: "Rămânem alături de tine după implementare, nu doar în ofertă." },
      ],
    },
    process: {
      eyebrow: "Proces",
      title: "Cum lucrăm, în 4 pași",
      steps: [
        { n: "01", title: "Analiză", desc: "Înțelegem afacerea, procesele și obiectivele tale." },
        { n: "02", title: "Soluție și plan", desc: "Alegem soluția potrivită nevoii și bugetului și îți prezentăm un plan clar, cu costuri și termene." },
        { n: "03", title: "Implementare", desc: "Configurăm, integrăm și instruim echipa." },
        { n: "04", title: "Suport pe termen lung", desc: "Optimizăm continuu și rămânem disponibili." },
      ],
    },
    about: {
      eyebrow: "Despre noi",
      title: "Misiunea noastră",
      mission: "Companiile plătesc pentru soluții digitale din care nu folosesc nici jumătate — apoi cumpără altele. Noi pornim invers: întâi scoatem tot ce se poate din ce ai deja, apoi completăm doar ce lipsește cu adevărat.",
      founderName: "Lilia Sviriniuc",
      founderRole: "Fondator",
      founderBio: "Șapte ani în management și implementare de soluții digitale: am coordonat echipe mari, pe care le-am optimizat și digitalizat, am implementat sisteme ERP în companii din Moldova. Peste tot am văzut același lucru: Office 365 redus la Word și stocare de fișiere, Odoo folosit pentru o singură funcție — deși acoperă aproape tot ce-i trebuie unei afaceri. Soluția era mereu să se cumpere altceva. Am pornit Switch Digital ca să schimb ordinea asta — și s-o fac pentru cât mai multe afaceri, nu doar pentru una.",
    },
    contact: {
      eyebrow: "Contact",
      title: "Hai să vedem unde pierzi timp",
      sub: "Îți facem un diagnostic al proceselor și primești un rezumat scris cu ce merită digitalizat și în ce ordine. Gratuit, fără obligații.",
      name: "Nume",
      namePh: "Numele tău",
      email: "Email",
      emailPh: "email@exemplu.md",
      phone: "Telefon",
      phonePh: "+373 ...",
      message: "Mesaj",
      messagePh: "Spune-ne despre afacerea ta și ce vrei să optimizezi.",
      send: "Trimite mesajul",
      sent: "Mesajul a fost trimis. Îți mulțumim!",
      error: "A apărut o eroare. Încearcă din nou.",
      detailsTitle: "Date de contact",
      follow: "Urmărește-ne",
      note: "Formularul va fi conectat la backendul securizat în Modulul 2.",
    },
    footer: { rights: "Toate drepturile rezervate.", tagline: "Tehnologia care îți optimizează afacerea." },
  },

  en: {
    nav: { services: "Services", about: "About", process: "Process", contact: "Contact" },
    cta: "Free assessment",
    hero: {
      badge: "Chișinău, Moldova",
      title: "Fewer apps, lower costs, processes that actually work.",
      sub: "For entrepreneurs and small businesses: we identify the right digital solutions and use them to the fullest — with no unnecessary licenses.",
      primary: "Free assessment",
      secondary: "See services",
    },
    switchRows: ["Digital solutions", "Optimization", "Established processes"],
    stats: [
      { k: "100%", v: "Tailored solutions" },
      { k: "4 steps", v: "From analysis to support" },
      { k: "0 hassle", v: "Everything explained simply" },
    ],
    services: {
      eyebrow: "Services",
      title: "What we do for your business",
      sub: "Digitize today, so you can use AI tomorrow.",
      items: [
        { icon: "search", title: "Process analysis & consulting", desc: "We analyze your processes and goals and show you exactly what's worth digitizing and in what order." },
        { icon: "layers", title: "Choosing the right solutions", desc: "We identify the SaaS tools that cover your needs at minimal cost — Microsoft 365, Google Workspace, Odoo — used to the fullest, with no unnecessary licenses." },
        { icon: "bolt", title: "Implementation & automation", desc: "We set up systems, automate repetitive tasks and connect everything you use." },
        { icon: "headset", title: "Optimization & support", desc: "We monitor, improve and stay with you for the long run." },
        { icon: "sparkles", title: "AI readiness & integration", desc: "AI only works on organized processes and clean data. We put those in order first, then integrate the tools that bring real value." },
      ],
    },
    values: {
      eyebrow: "Why Switch Digital",
      title: "Five principles that guide us",
      items: [
        { title: "Accessibility", desc: "Solutions any business can afford." },
        { title: "Simplicity", desc: "We turn technical complexity into clear steps." },
        { title: "Transparency", desc: "Honest advice, clear pricing and timelines from the start." },
        { title: "Expertise", desc: "We pick the right technology for your need, not the trendy one." },
        { title: "Partnership", desc: "We stay with you after implementation, not just in the quote." },
      ],
    },
    process: {
      eyebrow: "Process",
      title: "How we work, in 4 steps",
      steps: [
        { n: "01", title: "Analysis", desc: "We understand your business, processes and goals." },
        { n: "02", title: "Solution & plan", desc: "We choose the right solution for your need and budget and present a clear plan, with costs and timelines." },
        { n: "03", title: "Implementation", desc: "We configure, integrate and train your team." },
        { n: "04", title: "Long-term support", desc: "We keep optimizing and stay available." },
      ],
    },
    about: {
      eyebrow: "About us",
      title: "Our mission",
      mission: "Companies pay for digital tools they use less than half of — then buy more. We start the other way around: first we get everything out of what you already have, then we add only what's genuinely missing.",
      founderName: "Lilia Sviriniuc",
      founderRole: "Founder",
      founderBio: "Seven years in management and digital-solution implementation: I've led large teams, optimizing and digitizing them, and implemented ERP systems in companies across Moldova. Everywhere I saw the same thing: Office 365 reduced to Word and file storage, Odoo used for a single function, though it covers almost everything a business needs. The answer was always to buy something new. I started Switch Digital to reverse that order — and to do it for as many businesses as possible, not just one.",
    },
    contact: {
      eyebrow: "Contact",
      title: "Let's find where you're losing time",
      sub: "We assess your processes and you get a written summary of what's worth digitizing and in what order. Free, no strings attached.",
      name: "Name",
      namePh: "Your name",
      email: "Email",
      emailPh: "email@example.md",
      phone: "Phone",
      phonePh: "+373 ...",
      message: "Message",
      messagePh: "Tell us about your business and what you'd like to optimize.",
      send: "Send message",
      sent: "Message sent. Thank you!",
      error: "Something went wrong. Please try again.",
      detailsTitle: "Contact details",
      follow: "Follow us",
      note: "The form will be connected to the secure backend in Module 2.",
    },
    footer: { rights: "All rights reserved.", tagline: "Technology that optimizes your business." },
  },

  ru: {
    nav: { services: "Услуги", about: "О нас", process: "Процесс", contact: "Контакты" },
    cta: "Бесплатная диагностика",
    hero: {
      badge: "Кишинёв, Молдова",
      title: "Меньше приложений, ниже затраты, процессы, которые работают.",
      sub: "Для предпринимателей и малого бизнеса: подбираем подходящие цифровые решения и используем их на полную — без лишних лицензий.",
      primary: "Бесплатная диагностика",
      secondary: "Смотреть услуги",
    },
    switchRows: ["Цифровые решения", "Оптимизация", "Выстроенные процессы"],
    stats: [
      { k: "100%", v: "Решения под задачу" },
      { k: "4 шага", v: "От анализа до поддержки" },
      { k: "0 сложностей", v: "Всё объясняем простыми словами" },
    ],
    services: {
      eyebrow: "Услуги",
      title: "Что мы делаем для вашего бизнеса",
      sub: "Оцифруйте сегодня, чтобы завтра использовать AI.",
      items: [
        { icon: "search", title: "Анализ и консалтинг процессов", desc: "Разбираем ваши процессы и цели и показываем, что именно стоит оцифровать и в каком порядке." },
        { icon: "layers", title: "Подбор подходящих решений", desc: "Находим SaaS-инструменты, которые закрывают ваши задачи с минимальными затратами — Microsoft 365, Google Workspace, Odoo — используемые на полную, без лишних лицензий." },
        { icon: "bolt", title: "Внедрение и автоматизация", desc: "Настраиваем системы, автоматизируем рутинные задачи и связываем всё, чем вы пользуетесь." },
        { icon: "headset", title: "Оптимизация и поддержка", desc: "Следим, улучшаем и остаёмся рядом надолго." },
        { icon: "sparkles", title: "Подготовка и внедрение AI", desc: "AI работает только на упорядоченных процессах и чистых данных. Сначала приводим их в порядок, затем внедряем инструменты, которые дают реальную пользу." },
      ],
    },
    values: {
      eyebrow: "Почему Switch Digital",
      title: "Пять принципов, которыми мы руководствуемся",
      items: [
        { title: "Доступность", desc: "Решения, которые может позволить себе любой бизнес." },
        { title: "Простота", desc: "Превращаем техническую сложность в понятные шаги." },
        { title: "Прозрачность", desc: "Честные рекомендации, ясные цены и сроки с самого начала." },
        { title: "Экспертиза", desc: "Выбираем технологию под вашу задачу, а не модную." },
        { title: "Партнёрство", desc: "Остаёмся с вами после внедрения, а не только в коммерческом предложении." },
      ],
    },
    process: {
      eyebrow: "Процесс",
      title: "Как мы работаем, в 4 шага",
      steps: [
        { n: "01", title: "Анализ", desc: "Разбираемся в вашем бизнесе, процессах и целях." },
        { n: "02", title: "Решение и план", desc: "Подбираем решение под задачу и бюджет и представляем понятный план со сроками и стоимостью." },
        { n: "03", title: "Внедрение", desc: "Настраиваем, интегрируем и обучаем команду." },
        { n: "04", title: "Долгосрочная поддержка", desc: "Постоянно улучшаем и остаёмся на связи." },
      ],
    },
    about: {
      eyebrow: "О нас",
      title: "Наша миссия",
      mission: "Компании платят за цифровые решения, которые используют меньше чем наполовину — и покупают новые. Мы идём от обратного: сначала извлекаем всё возможное из того, что у вас уже есть, а затем добавляем только то, чего действительно не хватает.",
      founderName: "Lilia Sviriniuc",
      founderRole: "Основатель",
      founderBio: "Семь лет в управлении и внедрении цифровых решений: я руководила большими командами, оптимизировала и оцифровывала их работу, внедряла ERP-системы в компаниях Молдовы. Везде я видела одно и то же: Office 365, сведённый к Word и хранению файлов; Odoo, используемый для одной функции — хотя он закрывает почти всё, что нужно бизнесу. Решением всегда была покупка чего-то нового. Я основала Switch Digital, чтобы изменить этот порядок — и делать это для многих компаний, а не для одной.",
    },
    contact: {
      eyebrow: "Контакты",
      title: "Давайте посмотрим, где вы теряете время",
      sub: "Проводим диагностику ваших процессов, и вы получаете письменное резюме: что стоит оцифровать и в каком порядке. Бесплатно, без обязательств.",
      name: "Имя",
      namePh: "Ваше имя",
      email: "Email",
      emailPh: "email@primer.md",
      phone: "Телефон",
      phonePh: "+373 ...",
      message: "Сообщение",
      messagePh: "Расскажите о своём бизнесе и о том, что хотите улучшить.",
      send: "Отправить сообщение",
      sent: "Сообщение отправлено. Спасибо!",
      error: "Произошла ошибка. Попробуйте ещё раз.",
      detailsTitle: "Контактные данные",
      follow: "Мы в соцсетях",
      note: "Форма будет подключена к защищённому бэкенду в Модуле 2.",
    },
    footer: { rights: "Все права защищены.", tagline: "Технологии, которые оптимизируют ваш бизнес." },
  },
} as const;

export const contactInfo = {
  email: "contact@switchdigital.md",
  phone: "+373 60 360 488",
  location: "Chișinău, Moldova",
  facebook: "",
  linkedin: "https://www.linkedin.com/company/switchdigitalmd",
};
